# Generated by Django 3.0.3 on 2020-03-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymWebapp', '0006_auto_20200313_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
