# Generated by Django 3.0.3 on 2020-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymWebapp', '0007_auto_20200314_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='Dietplan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='Exercise',
            field=models.TextField(),
        ),
    ]
