# Generated by Django 3.0.3 on 2020-04-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymWebapp', '0008_auto_20200314_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pay_check',
            field=models.BooleanField(default=False),
        ),
    ]
